{% set name = "nimfa" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39cff2b86856d03ca8a3d9c38598034ecf1a768c325fd3a728bb9eadb8c6b919

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy >=1.7.0
    - python >={{ python_min }}
    - scipy >=0.12.0

test:
  imports:
    - nimfa
    - nimfa.datasets
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ai.stanford.edu/~marinka/nimfa/
  summary: A Python module for nonnegative matrix factorization
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING.txt
  doc_url: https://ai.stanford.edu/~marinka/nimfa/
  dev_url: https://github.com/mims-harvard/nimfa

extra:
  recipe-maintainers:
    - BastianZim
